import { i } from "@instantdb/react";
import type {
  GoalTimeframeLevel,
  GoalType,
  ItemStatus,
  PlanningCommitmentDomain,
  PlanningCommitmentLevel,
  PlanningCommitmentStatus,
  PlanningCycleStatus,
  PlanningCycleType,
} from "@/lib/domain/types";

export const appSchema = i.schema({
  entities: {
    userProfiles: i.entity({
      uid: i.string().indexed().unique(),
      email: i.string(),
      firstName: i.string().optional(),
      lastName: i.string().optional(),
      displayName: i.string().optional(),
      themeMode: i.string<"palette" | "cwm" | "college">().optional(),
      theme: i.string<"light" | "dark" | "cwm">(),
      palette: i.string<"ocean" | "sunset" | "forest" | "royal" | "candy" | "dusk" | "lava" | "mint">(),
      collegeTeamId: i.string().optional(),
      collegeTeamName: i.string().optional(),
      collegeLogoUrl: i.string().optional(),
      timezone: i.string(),
      retentionDays: i.number(),
      createdAt: i.string(),
      updatedAt: i.string(),
    }),
    goals: i.entity({
      ownerUid: i.string().indexed(),
      type: i.string<GoalType>().indexed(),
      parentGoalId: i.string().optional().indexed(),
      timeframeLevel: i.string<GoalTimeframeLevel>().indexed(),
      title: i.string(),
      description: i.string(),
      timeframe: i.string(),
      projectedStartDate: i.string().optional(),
      projectedEndDate: i.string().optional(),
      actualStartDate: i.string().optional(),
      actualEndDate: i.string().optional(),
      status: i.string<ItemStatus>().indexed(),
      percentComplete: i.number(),
      isFocus: i.boolean(),
      themeColor: i.string(),
      orderIndex: i.number(),
      createdAt: i.string(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
    tasks: i.entity({
      ownerUid: i.string().indexed(),
      parentGoalId: i.string().optional().indexed(),
      commitmentId: i.string().optional().indexed(),
      title: i.string(),
      notes: i.string(),
      dueDate: i.string().optional().indexed(),
      unplanned: i.boolean().optional(),
      originalDueDate: i.string().optional(),
      snoozedDueDate: i.string().optional(),
      snoozeCount: i.number().optional(),
      status: i.string<ItemStatus>().indexed(),
      percentComplete: i.number(),
      orderIndex: i.number(),
      createdAt: i.string(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
    journalEntries: i.entity({
      ownerUid: i.string().indexed(),
      title: i.string(),
      content: i.string(),
      mood: i.string().optional(),
      tags: i.json<string[]>(),
      relatedGoalId: i.string().optional().indexed(),
      createdAt: i.string(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
    habits: i.entity({
      ownerUid: i.string().indexed(),
      title: i.string(),
      cadence: i.string<"daily" | "weekly">().indexed(),
      targetCount: i.number(),
      status: i.string<"active" | "paused" | "archived">().indexed(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
    habitCheckins: i.entity({
      ownerUid: i.string().indexed(),
      habitId: i.string().indexed(),
      checkInDate: i.string().indexed(),
      notes: i.string().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    pushSubscriptions: i.entity({
      ownerUid: i.string().indexed(),
      endpoint: i.string().indexed().unique(),
      p256dh: i.string(),
      auth: i.string(),
      expirationTime: i.number().optional(),
      userAgent: i.string().optional(),
      createdAt: i.string(),
      updatedAt: i.string(),
      lastNotifiedAt: i.string().optional().indexed(),
    }),
    notificationPreferences: i.entity({
      ownerUid: i.string().indexed().unique(),
      dailyAgendaEnabled: i.boolean(),
      weeklyReviewEnabled: i.boolean(),
      dueTasksEnabled: i.boolean(),
      preferredHourLocal: i.number().optional(),
      timezone: i.string().optional(),
      quietHoursStart: i.string().optional(),
      quietHoursEnd: i.string().optional(),
      createdAt: i.string(),
      updatedAt: i.string(),
    }),
    notificationDeliveries: i.entity({
      ownerUid: i.string().indexed(),
      reminderType: i.string<"daily_agenda" | "weekly_review" | "due_tasks" | "test">().indexed(),
      channel: i.string<"push">(),
      status: i.string<"sent" | "failed" | "skipped">().indexed(),
      title: i.string().optional(),
      message: i.string().optional(),
      deliveredCount: i.number(),
      failedCount: i.number(),
      staleDeletedCount: i.number(),
      schedulerRunId: i.string().optional().indexed(),
      errorCode: i.string().optional(),
      errorMessage: i.string().optional(),
      createdAt: i.string().indexed(),
    }),
    planningCycles: i.entity({
      ownerUid: i.string().indexed(),
      cycleType: i.string<PlanningCycleType>().indexed(),
      startDate: i.string().indexed(),
      endDate: i.string().indexed(),
      status: i.string<PlanningCycleStatus>().indexed(),
      reviewSummary: i.string().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    planningCommitments: i.entity({
      ownerUid: i.string().indexed(),
      cycleId: i.string().indexed(),
      level: i.string<PlanningCommitmentLevel>().indexed(),
      domain: i.string<PlanningCommitmentDomain>().indexed(),
      title: i.string(),
      linkedGoalId: i.string().optional().indexed(),
      rank: i.number().indexed(),
      status: i.string<PlanningCommitmentStatus>().indexed(),
      carryoverFromCommitmentId: i.string().optional().indexed(),
      confidenceScore: i.number().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    dailyFocusPlans: i.entity({
      ownerUid: i.string().indexed(),
      planDate: i.string().indexed(),
      commitmentIds: i.json<string[]>(),
      taskIds: i.json<string[]>(),
      notes: i.string().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
  },
  links: {},
  rooms: {},
});

export type AppSchema = typeof appSchema;
