import { i } from "@instantdb/react";
import type { GoalType, ItemStatus } from "@/lib/domain/types";

export const appSchema = i.schema({
  entities: {
    userProfiles: i.entity({
      uid: i.string().indexed().unique(),
      email: i.string(),
      firstName: i.string().optional(),
      lastName: i.string().optional(),
      displayName: i.string().optional(),
      themeMode: i.string<"palette" | "cwm" | "college">().optional(),
      theme: i.string<"light" | "dark" | "cwm">(),
      palette: i.string<"ocean" | "sunset" | "forest" | "royal" | "candy" | "dusk" | "lava" | "mint">(),
      collegeTeamId: i.string().optional(),
      collegeTeamName: i.string().optional(),
      collegeLogoUrl: i.string().optional(),
      timezone: i.string(),
      retentionDays: i.number(),
      createdAt: i.string(),
      updatedAt: i.string(),
    }),
    goals: i.entity({
      ownerUid: i.string().indexed(),
      type: i.string<GoalType>().indexed(),
      title: i.string(),
      description: i.string(),
      timeframe: i.string(),
      projectedStartDate: i.string().optional(),
      projectedEndDate: i.string().optional(),
      actualStartDate: i.string().optional(),
      actualEndDate: i.string().optional(),
      status: i.string<ItemStatus>().indexed(),
      percentComplete: i.number(),
      isFocus: i.boolean(),
      themeColor: i.string(),
      orderIndex: i.number(),
      createdAt: i.string(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
    subgoals: i.entity({
      ownerUid: i.string().indexed(),
      goalId: i.string().indexed(),
      title: i.string(),
      description: i.string(),
      timeframe: i.string(),
      projectedStartDate: i.string().optional(),
      projectedEndDate: i.string().optional(),
      actualStartDate: i.string().optional(),
      actualEndDate: i.string().optional(),
      status: i.string<ItemStatus>().indexed(),
      percentComplete: i.number(),
      orderIndex: i.number(),
      createdAt: i.string(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
    tasks: i.entity({
      ownerUid: i.string().indexed(),
      subgoalId: i.string().indexed(),
      title: i.string(),
      notes: i.string(),
      dueDate: i.string().optional().indexed(),
      status: i.string<ItemStatus>().indexed(),
      percentComplete: i.number(),
      orderIndex: i.number(),
      createdAt: i.string(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
    journalEntries: i.entity({
      ownerUid: i.string().indexed(),
      title: i.string(),
      content: i.string(),
      mood: i.string().optional(),
      tags: i.json<string[]>(),
      relatedGoalId: i.string().optional().indexed(),
      createdAt: i.string(),
      updatedAt: i.string(),
      deletedAt: i.string().optional().indexed(),
      deletedBy: i.string().optional(),
      restoreUntil: i.string().optional().indexed(),
      purgeAt: i.string().optional().indexed(),
    }),
  },
  links: {},
  rooms: {},
});

export type AppSchema = typeof appSchema;
